### ISSUE TITLE
Img problem - not showing

### ISSUE THREAD

**Issue by Fichtner21** [frontendfunn/tailwind_2.x-webpack-setup-main#1]
Hi i have problem with <img src="">
structure:

i add into src. directory "images" and inside there i have a lot *.svg and *.png files, anyone not working when i try to display this in html file.
```
<img src="/src/images/example.png"> 
<img src="./src/images/example.png"> 
<img src="./../src/images/example.png"> 
```

and more combines. Please help how to solve this, i choose your great starter to small project but i have deadline in weekend :)

**Comment by frontendfunn** [comment]
@Fichtner21 Please Clone the Repo, Added Images.
You need to add the images path to the **JS** file, so that webpack can use appropriate loader to compile your assets.

**Comment by Fichtner21** [comment]
I know there is possible to import in js file but i my case i write about add images in html static file.

**Comment by frontendfunn** [comment]
@Fichtner21 can you provide with the repo
